# Generated by Django 3.0.4 on 2020-04-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
