# Generated by Django 3.0.4 on 2020-04-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200409_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['company'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.RenameField(
            model_name='stockprice',
            old_name='date_created',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='count_free',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='count_add',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='price_buy',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='price_sale',
        ),
        migrations.AddField(
            model_name='stockprice',
            name='close',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10000, max_length=20),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='high',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10000, max_length=20),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='low',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10000, max_length=20),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='open',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10000, max_length=20),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='per',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='vol',
            field=models.IntegerField(default=0),
        ),
    ]
