# Generated by Django 3.0.4 on 2020-03-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('0', 'Ожидание'), ('1', 'Купить'), ('2', 'Продать')], default='0', max_length=1)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
            options={
                'verbose_name': 'Робот',
                'verbose_name_plural': 'Роботы',
            },
        ),
    ]
