# Generated by Django 3.0.4 on 2020-03-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='action',
            field=models.CharField(choices=[('2', 'Продать'), ('0', 'Ожидание'), ('1', 'Купить')], default='0', max_length=1),
        ),
    ]
