# Generated by Django 3.0.4 on 2020-03-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('country', models.CharField(choices=[('3', 'Китай'), ('1', 'Украина'), ('5', 'Канада'), ('2', 'Россия'), ('0', 'Не указано'), ('4', 'США')], default='0', max_length=1)),
                ('city', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('fio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['fio'],
            },
        ),
        migrations.CreateModel(
            name='LogsAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('0', 'Ожидание'), ('1', 'Купить'), ('2', 'Продать')], max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('delete', models.BooleanField(default=0)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
            options={
                'verbose_name': 'Действие клиента',
                'verbose_name_plural': 'Действия клиента',
            },
        ),
        migrations.CreateModel(
            name='ClientStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('id_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock')),
            ],
        ),
    ]
