# Generated by Django 3.0.4 on 2020-03-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(choices=[('2', 'Россия'), ('5', 'Канада'), ('4', 'США'), ('3', 'Китай'), ('0', 'Не указано'), ('1', 'Украина')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='logsaction',
            name='action',
            field=models.CharField(choices=[('2', 'Продать'), ('0', 'Ожидание'), ('1', 'Купить')], max_length=1),
        ),
    ]
