# Generated by Django 3.0.4 on 2020-03-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200318_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='money',
            field=models.FloatField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(choices=[('2', 'Россия'), ('5', 'Канада'), ('4', 'США'), ('1', 'Украина'), ('3', 'Китай'), ('0', 'Не указано')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='logsaction',
            name='action',
            field=models.CharField(choices=[('1', 'Купить'), ('2', 'Продать'), ('0', 'Ожидание')], max_length=1),
        ),
    ]
